<a href="https://colab.research.google.com/github/xivan128/DLS_my/blob/master/NLP/%5Bseminar1%5Dtext_preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Прежде чем заняться решением какой-то задачи связанной с текстами, эти тексты нужно обработать.

### NLTK (Natural Language Toolkit) это удобная библиотека для работы с текстом.

In [1]:
!pip install --upgrade nltk 

     |████████████████████████████████| 1.5MB 2.5MB/s 
  Created wheel for nltk: filename=nltk-3.4.5-cp36-none-any.whl size=1449907 sha256=64740ed9a060f902852b0d2b057171f566c318f3a56184bf5712ca21784fb693
  Stored in directory: /root/.cache/pip/wheels/96/86/f6/68ab24c23f207c0077381a5e3904b2815136b879538a24b483
Successfully built nltk
  Found existing installation: nltk 3.2.5
    Uninstalling nltk-3.2.5:
      Successfully uninstalled nltk-3.2.5


In [0]:
import nltk

In [0]:
# Сейчас должно открыться окно загрузки данных nltk
#nltk.download()

**Токенизация текста**

In [4]:
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [5]:
from nltk.tokenize import sent_tokenize, word_tokenize
 
data = "All work and no play makes jack a dull boy, all work and no play"
print(word_tokenize(data))

['All', 'work', 'and', 'no', 'play', 'makes', 'jack', 'a', 'dull', 'boy', ',', 'all', 'work', 'and', 'no', 'play']


In [7]:
print(sent_tokenize("I was going home when she rung. It was a surprise."))

['I was going home when she rung.', 'It was a surprise.']


**Удаление стоп слов, которые часто встречаются, но не несут особого смысла. Они могут мешать.**

In [8]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [0]:
from nltk.corpus import stopwords
stopWords = set(stopwords.words('english'))

In [10]:
len(stopWords)

179

In [0]:
res = [word for word in word_tokenize(data) if word not in stopWords]

In [14]:
stopWords

{'a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 'her',
 'here',
 'hers',
 'herself',
 'him',
 'himself',
 'his',
 'how',
 'i',
 'if',
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it's",
 'its',
 'itself',
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 'r

In [15]:
# Пропал токен 'no'
res

['All', 'work', 'play', 'makes', 'jack', 'dull', 'boy', ',', 'work', 'play']

**Так же для каждого слова мы можем делать stemming, выделять его корень.**

In [0]:
from nltk.stem import PorterStemmer
words = ["game", "gaming", "gamed", "games", "compacted"]

In [17]:
ps = PorterStemmer()
list(map(ps.stem, words))

['game', 'game', 'game', 'game', 'compact']

**Лемматизация**

In [0]:
raw = """DENNIS: Listen, strange women lying in ponds distributing swords
is no basis for a system of government.  Supreme executive power derives from
a mandate from the masses, not from some farcical aquatic ceremony."""
tokens = word_tokenize(raw)

In [21]:
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [22]:
wnl = nltk.WordNetLemmatizer()
print(list(map(wnl.lemmatize, tokens)))

['DENNIS', ':', 'Listen', ',', 'strange', 'woman', 'lying', 'in', 'pond', 'distributing', 'sword', 'is', 'no', 'basis', 'for', 'a', 'system', 'of', 'government', '.', 'Supreme', 'executive', 'power', 'derives', 'from', 'a', 'mandate', 'from', 'the', 'mass', ',', 'not', 'from', 'some', 'farcical', 'aquatic', 'ceremony', '.']


In [23]:
# Если мы укажем часть речи слова
wnl.lemmatize('is', 'v')

'be'

**Part of speech tagging. NLTK умеет расставлять части речи словам в предложении.**

In [24]:
nltk.download('averaged_perceptron_tagger')

[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger.zip.


True

In [0]:
sentences = nltk.sent_tokenize(data)   
for sent in sentences:
    print(nltk.pos_tag(nltk.word_tokenize(sent)))

![POStags](POStags.png)

**Парсинг**

In [26]:
from nltk.corpus import treebank
nltk.download('treebank')

[nltk_data] Downloading package treebank to /root/nltk_data...
[nltk_data]   Unzipping corpora/treebank.zip.


True

In [27]:
t = treebank.parsed_sents('wsj_0001.mrg')[0]
t.draw()
# Сейчас должна открыться картинка.

TclError: ignored

### Регулярные выражения

Исчерпывающий пост https://habr.com/ru/post/349860/

**Рассмотрим несколько распространенных примеров использования регулярок.**

In [0]:
import re
# С помощью рег. выражения можно искать, заменять и сентезировать строки по шаблонам
# Парочка простых примеров

In [29]:
word = 'supercalifragilisticexpialidocious'
re.findall('[aeiou]|super', word)

['super', 'a', 'i', 'a', 'i', 'i', 'i', 'e', 'i', 'a', 'i', 'o', 'i', 'o', 'u']

In [30]:
re.findall('\d+', 'There is some numbers: 49 and 432')

['49', '432']

In [31]:
re.sub('[,\.?!]',' ','How, to? split. text!').split()

['How', 'to', 'split', 'text']

In [34]:
re.sub('[^A-z]',' &','I 123 can 45 play 67 football').split()

['I',
 '&',
 '&',
 '&',
 '&',
 '&can',
 '&',
 '&',
 '&',
 '&play',
 '&',
 '&',
 '&',
 '&football']

![Regexp](Regexp.png)

In [0]:
#!pip install spacy

### Spacy
#### Это еще одна быстрая библиотека с решениями для NLP.
#### В ней реализованы многие вещи, которые есть и в NLTK

**Например NER (Named entities recognition)**

In [0]:
#!python -m spacy download en 

In [0]:
import en_core_web_sm
import spacy
nlp = en_core_web_sm.load()

In [37]:
doc = nlp(u'Apple is looking at buying U.K. startup for $1 billion')

for ent in doc.ents:
    print(ent.text, ent.start_char, ent.end_char, ent.label_)

Apple 0 5 ORG
U.K. 27 31 GPE
$1 billion 44 54 MONEY


## 20 newsgroups это датасет с 18000 новостей, сгруппированных по 20 темам.

In [38]:
from sklearn.datasets import fetch_20newsgroups
newsgroups_train = fetch_20newsgroups(subset='train')

In [39]:
list(newsgroups_train.target_names)

['alt.atheism',
 'comp.graphics',
 'comp.os.ms-windows.misc',
 'comp.sys.ibm.pc.hardware',
 'comp.sys.mac.hardware',
 'comp.windows.x',
 'misc.forsale',
 'rec.autos',
 'rec.motorcycles',
 'rec.sport.baseball',
 'rec.sport.hockey',
 'sci.crypt',
 'sci.electronics',
 'sci.med',
 'sci.space',
 'soc.religion.christian',
 'talk.politics.guns',
 'talk.politics.mideast',
 'talk.politics.misc',
 'talk.religion.misc']

In [40]:
newsgroups_train.filenames.shape

(11314,)

In [41]:
newsgroups_train.target.shape

(11314,)

In [0]:
cats = ['alt.atheism', 'sci.space']
newsgroups_train = fetch_20newsgroups(subset='train', categories=cats)

In [43]:
newsgroups_train.filenames.shape

(1073,)

In [44]:
newsgroups_train.data[0]

'From: bil@okcforum.osrhe.edu (Bill Conner)\nSubject: Re: Not the Omni!\nNntp-Posting-Host: okcforum.osrhe.edu\nOrganization: Okcforum Unix Users Group\nX-Newsreader: TIN [version 1.1 PL6]\nLines: 18\n\nCharley Wingate (mangoe@cs.umd.edu) wrote:\n: \n: >> Please enlighten me.  How is omnipotence contradictory?\n: \n: >By definition, all that can occur in the universe is governed by the rules\n: >of nature. Thus god cannot break them. Anything that god does must be allowed\n: >in the rules somewhere. Therefore, omnipotence CANNOT exist! It contradicts\n: >the rules of nature.\n: \n: Obviously, an omnipotent god can change the rules.\n\nWhen you say, "By definition", what exactly is being defined;\ncertainly not omnipotence. You seem to be saying that the "rules of\nnature" are pre-existant somehow, that they not only define nature but\nactually cause it. If that\'s what you mean I\'d like to hear your\nfurther thoughts on the question.\n\nBill\n'

In [45]:
newsgroups_train.target[:10]

array([0, 1, 1, 1, 0, 1, 1, 0, 0, 0])

### Давайте векторизуем эти тексты с помощью TF-IDF

In [0]:
from sklearn.feature_extraction.text import TfidfVectorizer
categories = ['alt.atheism', 'talk.religion.misc',
              'comp.graphics', 'sci.space']
newsgroups_train = fetch_20newsgroups(subset='train',
                                      categories=categories)

#### Некоторые параметры TfidfVectorizer: 
#### input : string {‘filename’, ‘file’, ‘content’}
#### lowercase : boolean, default True
#### preprocessor : callable or None (default)
#### tokenizer : callable or None (default)
#### stop_words : string {‘english’}, list, or None (default)'
#### ngram_range : tuple (min_n, max_n)
#### max_df : float in range [0.0, 1.0] or int, default=1.0
#### min_df : float in range [0.0, 1.0] or int, default=1
#### max_features : int or None, default=None

In [47]:
vectorizer = TfidfVectorizer()
vectors = vectorizer.fit_transform(newsgroups_train.data)
vectors.shape

(2034, 34118)

In [49]:
vectorizer = TfidfVectorizer(lowercase=False)
vectors = vectorizer.fit_transform(newsgroups_train.data)
vectors.shape

(2034, 42307)

In [50]:
vectorizer = TfidfVectorizer(min_df=0.2)
vectors = vectorizer.fit_transform(newsgroups_train.data)
vectors.shape

(2034, 90)

In [51]:
vectorizer = TfidfVectorizer(max_df=0.9)
vectors = vectorizer.fit_transform(newsgroups_train.data)
vectors.shape

(2034, 34111)

In [52]:
# Эта штука работает дольше
vectorizer = TfidfVectorizer(tokenizer=nltk.word_tokenize)
vectors = vectorizer.fit_transform(newsgroups_train.data)
vectors.shape

(2034, 40925)

In [0]:
vector = vectors.todense()[1]

In [65]:
vector[vector != 0].shape

(1, 141)

In [0]:
from nltk.corpus import stopwords
stopWords = set(stopwords.words('english'))
wnl = nltk.WordNetLemmatizer()

In [0]:
def preproc1(text):
    return ' '.join([wnl.lemmatize(word) for word in word_tokenize(text.lower()) if word not in stopWords])

In [0]:
# Протестируем
st = "Oh, I think I ve landed Where there are miracles at work,  For the thirst and for the hunger Come the conference of birds"

In [58]:
preproc1(st)

'oh , think landed miracle work , thirst hunger come conference bird'

In [66]:
%%time
vectorizer = TfidfVectorizer(preprocessor=preproc1)
vectors = vectorizer.fit_transform(newsgroups_train.data)
vectors.shape

CPU times: user 8.2 s, sys: 4.14 ms, total: 8.2 s
Wall time: 8.22 s


In [67]:
vectors.shape

(2034, 31717)

**Давайте сравним скорость с лемматайзером spacy**

In [62]:
vector

matrix([[0., 0., 0., ..., 0., 0., 0.]])

In [0]:
import spacy
nlp = spacy.load('en')

In [0]:
def preproc2(text):
    return ' '.join([token.lemma_ for token in nlp(text.lower()) if token not in stopWords])

In [0]:
preproc2(st)

In [0]:
%%time
vectorizer = TfidfVectorizer(preprocessor=preproc2)
vectors = vectorizer.fit_transform(newsgroups_train.data)

In [0]:
vectors.shape

**Как видим spacy делает кучу всего сразу, хотя мы хотим только лемму. Поэтому работает дольше (сильно).**

In [68]:
vectorizer = TfidfVectorizer(max_features=1500, preprocessor=preproc1)
vectors = vectorizer.fit_transform(newsgroups_train.data)
vectors.shape

(2034, 1500)

### Можем посмотреть на косинусную меру между векторами

#### В этих векторах очень много нулей, поэтому по умолчанию они записываются как sparce matrix для экономии памяти

In [0]:
import numpy as np
from numpy.linalg import norm

In [70]:
type(vectors)

scipy.sparse.csr.csr_matrix

In [71]:
newsgroups_train.target[:10]

array([1, 3, 2, 0, 2, 0, 2, 1, 2, 1])

In [72]:
np.unique(newsgroups_train.target)

array([0, 1, 2, 3])

In [0]:
dense_vectors = vectors.todense()

In [74]:
dense_vectors.shape

(2034, 1500)

In [0]:
def cosine_sim(v1, v2):
    # v1, v2 (1 x dim)
    return np.array(v1 @ v2.T / norm(v1) / norm(v2))[0][0]

In [76]:
cosine_sim(dense_vectors[1], dense_vectors[1])

1.0000000000000002

In [0]:
cosines = []
for i in range(10):
    cosines.append(cosine_sim(dense_vectors[0], dense_vectors[i]))

In [78]:
# [1, 3, 2, 0, 2, 0, 2, 1, 2, 1]
cosines

[1.0,
 0.013234402729127756,
 0.0023691156170334185,
 0.02235694113966816,
 0.03646854513673787,
 0.012104582157857174,
 0.0274475883361666,
 0.12025122915826814,
 0.016803067934527717,
 0.01918954831470175]

**Cамым близким оказался вектор из той же категории**

**Так же можно попробовать сделать классификацию на основе этих векторов**

In [0]:
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.linear_model import SGDClassifier

In [0]:
svc = svm.SVC()

In [0]:
X_train, X_test, y_train, y_test= train_test_split(dense_vectors, newsgroups_train.target, test_size=0.2)

In [82]:
y_train.shape, y_test.shape

((1627,), (407,))

In [83]:
%%time
svc.fit(X_train, y_train)

CPU times: user 8.59 s, sys: 1.86 ms, total: 8.59 s
Wall time: 8.6 s


SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [84]:
from sklearn.metrics.classification import accuracy_score

/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:144: FutureWarning: The sklearn.metrics.classification module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.metrics. Anything that cannot be imported from sklearn.metrics is now part of the private API.
  warnings.warn(message, FutureWarning)


In [85]:
accuracy_score(y_test, svc.predict(X_test))

0.941031941031941

In [0]:
sgd = SGDClassifier()

In [87]:
sgd.fit(X_train, y_train)

SGDClassifier(alpha=0.0001, average=False, class_weight=None,
              early_stopping=False, epsilon=0.1, eta0=0.0, fit_intercept=True,
              l1_ratio=0.15, learning_rate='optimal', loss='hinge',
              max_iter=1000, n_iter_no_change=5, n_jobs=None, penalty='l2',
              power_t=0.5, random_state=None, shuffle=True, tol=0.001,
              validation_fraction=0.1, verbose=0, warm_start=False)

In [88]:
accuracy_score(y_test, sgd.predict(X_test))

0.9361179361179361

### Попробуем классифицировать на основе embeddings

In [0]:
categories = ['alt.atheism', 'talk.religion.misc',
              'comp.graphics', 'sci.space']
newsgroups_train = fetch_20newsgroups(subset='train',
                                      categories=categories)

In [90]:
import gensim.downloader as api
embeddings = api.load('glove-twitter-25')

[====================================--------------] 73.5% 77.0/104.8MB downloaded

/usr/local/lib/python3.6/dist-packages/smart_open/smart_open_lib.py:410: UserWarning: This function is deprecated, use smart_open.open instead. See the migration notes for details: https://github.com/RaRe-Technologies/smart_open/blob/master/README.rst#migrating-to-the-new-open-function
  'See the migration notes for details: %s' % _MIGRATION_NOTES_URL


In [0]:
def vectorize_sum(comment):
    """
    implement a function that converts preprocessed comment to a sum of token vectors
    """
    embedding_dim = embeddings.vectors.shape[1]
    features = np.zeros([embedding_dim], dtype='float32')
    
    # наш preproc1
    words = preproc1(comment).split()
    for word in words:
        if word in embeddings:
            features += embeddings[f'{word}']
    
    return features

In [92]:
vectorize_sum('I can swim')

array([-1.0690e+00,  1.4740e-01,  1.5582e-01, -4.5698e-01, -8.0204e-01,
        4.7470e-01,  1.2425e+00, -9.0298e-01,  7.0123e-01, -6.7615e-02,
       -1.8999e-01, -1.7142e-01, -3.1259e+00,  1.7241e-01, -3.3581e-03,
        1.1369e+00,  4.6636e-01, -1.0841e+00,  4.3825e-01,  2.0401e-03,
       -1.0665e+00,  7.0757e-01,  9.5706e-01, -3.5242e-01,  8.5145e-01],
      dtype=float32)

In [0]:
X_wv = np.stack([vectorize_sum(text) for text in newsgroups_train.data])
X_train_wv, X_test_wv, y_train, y_test = train_test_split(X_wv, newsgroups_train.target, test_size=0.2)

In [94]:
X_train_wv.shape, X_test_wv.shape

((1627, 25), (407, 25))

In [95]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_auc_score

wv_model = LogisticRegression().fit(X_train_wv, y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


In [96]:
accuracy_score(y_test, wv_model.predict(X_test_wv))

0.7027027027027027